# Building a Java project
language: java

# We can specify a list of JDKs to be used for testing
jdk:
 - openjdk11
after_success:
  - bash <(curl -s https://codecov.io/bash)
  notifications:
 email:
   - 1871554380@qq.com(replace by your e-mail)

